### ISSUE TITLE
on click Issue in table style dropdown list 

### ISSUE THREAD

**Issue by yoursantu** [tylerecouture/summernote-table-styles#3]
This Plug-in pretty awesome!! works better on static website. but in dynamic website, whenever choose table style from popover dropdown, it will redirects to "#". i.e. if my website url is http://localhost/myproject/index.php?route=common/dashboard
then it will redirect to  http://localhost/myproject/# when table style is selected!!
so it needs to prevent from default, so i have added additional parameter to the callback on line number 71
`callback: function($dropdown) {
              $dropdown.find("a").each(function(e) {
                $(this).click(function() {
                  self.updateTableStyles(this);
                   e.preventDefault();
                });
              });
            }`

**Comment by tylerecouture** [comment]
Thanks! Can you make a pull request?
